raise error when jsonfile not found

diff --git a/rsolo b/rsolo
--- a/rsolo
+++ b/rsolo
@@ -159,6 +159,12 @@ _setup_ssh() {
         hostname=${param[0]}
         jsonfile=nodes/${node_name}.json
     fi
+
+    if [[ ! -e $jsonfile ]] ; then
+        echo "$jsonfile file not found" >&2
+        exit 1
+    fi
+
     ssh_cmd="ssh $ssh_options $hostname"
 }
 
